name: Lint and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint_and_typecheck:
    name: lint and typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install poetry and dependencies
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry==1.7
          poetry install
      - name: lint
        run: poetry run ruff check .
      - name: typecheck
        run: poetry run mypy snap_http/

  unit_test:
    name: tox unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install poetry and dependencies
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry==1.7
          poetry install
      - name: install additional python versions
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install -y python3.8 python3.9 python3.10 python3.11 python3.12
          sudo apt install -y python3.8-distutils python3.9-distutils
      - name: tox unit test
        run: poetry run tox

  integration_test:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
        # Access to the snapd socket requires root privileges, so these
        # tests need to be run as root.
      - uses: actions/checkout@v4
      - name: install python dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip install poetry==1.7
          sudo poetry install
      - name: snapd setup
        run: |
          sudo apt install -y snapd
          sudo systemctl start snapd.service
      - name: integration test
        run: sudo poetry run pytest tests/integration
