name: Lint and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint_and_unit_test:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Python dependencies
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install poetry==1.7
          poetry install

      - name: Lint
        run : |
          poetry run ruff check .
          poetry run mypy snap_http/

      - name: Unit Test
        run: poetry run tox

  integration_test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Python dependencies
        # since access to the snapd socket requires root privileges,
        # the tests (pytest) have to be run as root
        run: |
          curl -sSL https://install.python-poetry.org | sudo python -
          sudo /root/.local/bin/poetry config virtualenvs.create false &&
          sudo /root/.local/bin/poetry install --no-root

      - name: Set up Snapd
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo systemctl start snapd.service

      - name: Integration Test
        run: sudo python -m pytest --cov=snap_http/ tests/
